version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports: 
    - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
    volumes:
      - mongo-database:/data/db
  
  redis:
    image: redis

volumes:
  mongo-database:
